#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : enable

#include "GaussianBlur.glsl"

layout(binding = 0) uniform texture2D inImage;
layout(r8, binding = 1) uniform writeonly image2D outImage;
layout(binding = 2) uniform sampler linearSampler;


layout(local_size_x = KERNAL_SIZE, local_size_y = 1, local_size_z = 1) in;


void main()
{
#include "BlurX_Base.glsl"
}
