#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : enable

#include "ClusteredLighting.glsl"


layout(std430, binding = 0) buffer count
{
	uint counter;
};

layout(std430, binding = 1) buffer visibleFroxles
{
	uint x;
	uint y;
	uint z;
};


layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;


void main()
{
	x = counter;
	y = 1;
	z = 1;
}